name: lattos_tuner
description: "Afinador cromático com presets de afinação salvos (ex.: SOAD – Drop C)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  record: ^6.2.1
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
